language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-gnutls-dev librtmp-dev
install:
  - python setup.py install
  - python -c 'print(__import__("requests").__version__)'
script: nosetests
