language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
before_install:
  - sudo apt-get update
  - sudo apt-get install libcurl4-gnutls-dev librtmp-dev
install:
  - pip install pycurl flake8 --use-mirrors
  - python setup.py install
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 stripe; fi
script: python -W always setup.py test
